; Exercise 3.78. Consider the problem of designing a signal-processing system to study the homogeneous second-order linear differential equation <...>. The output stream, modeling y, is generated by a network that contains a loop. This is because the value of d2y/dt2 depends upon the values of y and dy/dt and both of these are determined by integrating d2y/dt2. The diagram we would like to encode is shown in figure 3.35. Write a procedure solve-2nd that takes as arguments the constants a, b, and dt and the initial values y0 and dy0 for y and dy/dt and generates the stream of successive values of y.

(load "77.scm")

(define (solve-2nd a b dt y0 dy0)
  (define y (integral (delay dy) y0 dt))
  (define dy (integral (delay ddy) dy0 dt))
  (define ddy (add-streams (scale-stream y b) (scale-stream dy a)))
  y)

(assert (stream-ref (solve-2nd 1 0 0.001 1 1) 1000) 2.716923932235896) ; e ~ 2.71828182846
(assert (stream-ref (solve-2nd 0 -1 0.0001 1 0) 10472) 0.5000240628699462) ; cos pi/3 = 0.5
(assert (stream-ref (solve-2nd 0 -1 0.0001 0 1) 5236) 0.5000141490501059) ; sin pi/6 = 0.5
